folder_in: '/home/user2/tst'
folder_out: '/home/user2/out'
folder_ext:  '/home/user2/folder1'
folder_ext2: '/home/user2/folder2'
user: 'user2'
passwd: "11"
package_name: 'p7zip-full.deb'
IP_address: '0.0.0.0'
type: '7z'
